### ISSUE TITLE
Calendar has right time, but wrong day, when viewed overseas

### ISSUE THREAD

**Issue by jidanni** [osmus/mappingusa.org-redirects#1]
On https://openstreetmap.us/events/mapping-usa/
the time is correct, but the days are wrong. In Taipei it is Saturday.
![Screenshot 2024-01-11 22 06 56](https://github.com/osmus/mappingusa.org-redirects/assets/1230959/56e877e4-d9a9-47f1-9df7-f0043f2f93b3)
Same for the next day further down. @quincylvania 
![Screenshot 2024-01-20 01 55 48](https://github.com/osmus/mappingusa.org-redirects/assets/1230959/bfe7ae26-4459-4ac3-82f7-9db6bd554ee0)
Yes I know it is really confusing.
Anyway, Friday 3AM should be Saturday 3AM. Sat. 12:00 AM should be Sunday 12:00 AM, (00:00 clearer too.)
Yes, "End of Friday" is not an error, because that's not automatically generated, so not part of the bug.

**Comment by quincylvania** [comment]
@jidanni Thanks, this was fixed for the first date before the conference.

**Comment by jidanni** [comment]
Dear @quincylvania yes it's fixed for the first day, but as you can see below the second day is still broken. It should say Sunday the 21st.
![Screenshot_20240131_154857_Chrome Beta.jpg](https://github.com/osmus/mappingusa.org-redirects/assets/1230959/a7237f73-4891-434e-a29b-fefe0247bfb3)
